# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deef5284e2bd5db789b6021855d2bfa125656bbfc9b3b17e6bc99a77125ae76e247aa0bb4da8c905bbf31c86bc336891675a18cf1e03ab44e99ef96d83691ae5

test:
  secret_key_base: 132f8f10d7544ab2699832196fac6faa79cf0f718938d112210f5a0ff303a4b264a70f54d8dbc71af7aa107fd16f4bae18680c8aa97f7b6784076193bea94485

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
